# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_menuBar_statusBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.motorbike = QtWidgets.QLabel(self.centralwidget)
        self.motorbike.setGeometry(QtCore.QRect(70, 30, 621, 391))
        self.motorbike.setText("")
        self.motorbike.setPixmap(QtGui.QPixmap("XSR 125.png"))
        self.motorbike.setScaledContents(True)
        self.motorbike.setObjectName("motorbike")
        self.XSR125_btn = QtWidgets.QPushButton(self.centralwidget)
        self.XSR125_btn.setGeometry(QtCore.QRect(210, 440, 113, 32))
        self.XSR125_btn.setObjectName("pushButton")
        self.XSR125_btn.clicked.connect(self.show_XSR125)
        self.XS650_btn = QtWidgets.QPushButton(self.centralwidget)
        self.XS650_btn.setGeometry(QtCore.QRect(420, 440, 113, 32))
        self.XS650_btn.setObjectName("pushButton_2")
        self.XS650_btn.clicked.connect(self.show_XS650)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 773, 34))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def show_XSR125(self):
        self.motorbike.setPixmap(QtGui.QPixmap("XSR 125.png"))
    
    def show_XS650(self):
        self.motorbike.setPixmap(QtGui.QPixmap("XS 650.png"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "My Yamaha motorbikes"))
        self.XSR125_btn.setText(_translate("MainWindow", "XSR 125"))
        self.XS650_btn.setText(_translate("MainWindow", "XS 650"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
